name: dart_triage_updater
description: A sample command-line application.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  github: ^9.17.0
  http: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
