name: dart_pr_dashboard
description: A new Flutter project.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.5.1
  firebase_core: ^2.9.0
  firebase_database: ^10.1.0
  github: ^9.11.0
  intl4x: ^0.5.0
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0
  vtable: ^0.4.0
  fl_chart: ^0.63.0
  collection: ^1.17.2
  dart_triage_updater:
    git:
      url: git@github.com:mosuem/dart_triage_updater.git
      ref: useTimelines

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.2

flutter:
  uses-material-design: true
  
dependency_overrides:
  collection: 1.18.0