name: compute_statistics
description: Compute statistics for the dashboard.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  dart_triage_updater:
    path: ../dart_triage_updater
  github: ^9.17.0
  collection: ^1.18.0
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
